version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2
    steps:
      # GIT
      - checkout
      # SYSTEM
      - run:
          name: Install System Packages
          command: sudo apt-get update
      # COMPOSER
      - run:
          name: Install Composer Dependencies
          command: composer install
      # TESTS
      - run:
          name: Run Tests
          command: phpdbg -qrr vendor/bin/phpunit --coverage-html build/coverage-report
      - store_artifacts:
          path:  build/coverage-report
