version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  php-cs:
    docker:
      - image: cimg/php:7.4
    working_directory: ~/php-datatypes
    steps:
      - checkout
      - run:
          name: Update System
          command: sudo apt-get update
      - run:
          name: Install CLOC
          command: sudo apt-get -y install cloc
      - run:
          name: PHP Version
          command: php -v
      - run:
          name: Project's Statistics
          command: git ls-files | xargs cloc
      - run:
          name: Composer Install
          command: composer install
      - run:
          name: Check Coding Standards for PHPv7.4
          command: |
            vendor/bin/phpcs --standard=PSR2 --exclude=Squiz.WhiteSpace.ControlStructureSpacing src
            vendor/bin/phpcs --standard=PSR2 --exclude=Squiz.WhiteSpace.ControlStructureSpacing tests

  php-74:
    docker:
      - image: cimg/php:7.4
    working_directory: ~/php-datatypes
    steps:
      - checkout
      - run:
          name: Composer Install
          command: composer install
      - run:
          name: Run Tests for PHPv7.4
          command: phpdbg -qrr vendor/bin/phpunit --coverage-clover ~/build/coverage-report
      - store_artifacts:
          path: ~/build/coverage-report
      - codecov/upload:
          file: ~/build/coverage-report

  php-80:
    docker:
      - image: cimg/php:8.0
    working_directory: ~/php-datatypes
    steps:
      - checkout
      - run:
          name: Composer Install
          command: composer install
      - run:
          name: Run Tests for PHPv8.0
          command: phpdbg -qrr vendor/bin/phpunit

  php-81:
    docker:
      - image: cimg/php:8.1
    working_directory: ~/php-datatypes
    steps:
      - checkout
      - run:
          name: Composer Install
          command: composer install
      - run:
          name: Run Tests for PHPv8.1
          command: phpdbg -qrr vendor/bin/phpunit

workflows:
  ci-flow:
    jobs:
      - php-cs
      - php-74:
          requires:
            - php-cs
      - php-80:
          requires:
            - php-cs
      - php-81:
          requires:
            - php-cs
