version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.2
    working_directory: ~/php-datatypes
    steps:
      # GIT
      - checkout
      # SYSTEM
      - run:
          name: Install System Packages
          command: sudo apt-get update
      # COMPOSER
      - run:
          name: Install Composer Dependencies
          command: composer install
      # TESTS
      - run:
          name: Run Tests
          command: phpdbg -qrr vendor/bin/phpunit --coverage-html build/coverage-report
      - run:
          name: Check coding standards in /src
          command: vendor/bin/phpcs --standard=PSR2 --exclude=Squiz.WhiteSpace.ControlStructureSpacing src
      - run:
          name: Check coding standards in /tests
          command: vendor/bin/phpcs --standard=PSR2 --exclude=Squiz.WhiteSpace.ControlStructureSpacing tests
      - store_artifacts:
          path:  build/coverage-report
      
