version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    docker:
      - image: circleci/php:7.4
    working_directory: ~/php-datatypes
    steps:
      # GIT
      - checkout
      # SYSTEM
      - run:
          name: Install System Packages
          command: sudo apt-get update
      - run:
          name: Install CLOC
          command: sudo apt-get -y install cloc
      # COMPOSER
      - run:
          name: Install Composer Dependencies
          command: composer install
      # STATISTICS
      - run:
          name: Project's Statistics
          command: git ls-files | xargs cloc
      # TESTS
      - run:
          name: Run Tests
          command: phpdbg -qrr vendor/bin/phpunit --coverage-clover build/coverage-report
      - run:
          name: Check coding standards in /src
          command: vendor/bin/phpcs --standard=PSR2 --exclude=Squiz.WhiteSpace.ControlStructureSpacing src
      - run:
          name: Check coding standards in /tests
          command: vendor/bin/phpcs --standard=PSR2 --exclude=Squiz.WhiteSpace.ControlStructureSpacing tests
      - store_artifacts:
          path: build/coverage-report
      - codecov/upload:
          file: build/coverage-report

