name: Release

on:
  push:
    tags: "*"
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  getVersion:
    runs-on: ubuntu-latest

    outputs:
      currentVersion: ${{ steps.currentVersion.outputs.currentVersion }}
      nextVersion: ${{ steps.nextVersion.outputs.nextVersion }}

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure committer
      run: |
        git config user.name "HRA Digital"
        git config user.email "github@hradigital.com"

    - name: Get Next Version
      id: semver
      uses: ietf-tools/semver-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref_name }}
        majorList: break
        patchAll: true

    - name: Current version
      id: currentVersion
      run: echo "::set-output name=currentVersion::$current"

    - name: Next version
      id: nextVersion
      run: echo "::set-output name=nextVersion::$nextStrict"

  generateChangeLog:
    runs-on: ubuntu-latest
    needs: getVersion

    outputs:
      currentVersion: ${{ needs.getVersion.outputs.currentVersion }}
      nextVersion: ${{ needs.getVersion.outputs.nextVersion }}
      changeLogText: ${{ steps.changelog.outputs.changelog }}

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - run: echo Previous - ${{ needs.getVersion.outputs.currentVersion }}
    - run: echo Current - ${{ needs.getVersion.outputs.nextVersion }}

    - name: Generate CHANGELOG
      id: changelog
      uses: heinrichreimer/github-changelog-generator-action@v2.3
      with:
        token: ${{ github.token }}
        sinceTag: ${{ needs.getVersion.outputs.currentVersion }}
        excludeTags:
        compareLink: true
        breakingLabel: Breaking changes
        breakingLabels: break, breaking, breaking changes
        headerLabel: Release

  dorelease:
    runs-on: ubuntu-latest
    needs: generateChangeLog

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure committer
      run: |
        git config user.name "HRA Digital"
        git config user.email "github@hradigital.com"

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name:  ${{ needs.generateChangeLog.outputs.nextVersion }}
        release_name: v${{ needs.generateChangeLog.outputs.nextVersion }}
        body: ${{ needs.generateChangeLog.outputs.changeLogText }}
        draft: false
        prerelease: false
